#공통 설정
spring:
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: false
        physical_naming_strategy: kr.bookstorage.config.ImprovedNamingStrategy
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl

  datasource:
    url: jdbc:mysql://175.124.95.216:3306/book_storage
    username: root
    password: ksb
    driver-class-name: com.mysql.jdbc.Driver
    test-on-borrow: true
    validation-query: select 1 from dual

  redis:
    host: localhost
    password:
    port: 6379

  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

management:
  security:
    sessions: NEVER

logging:
  level:
    kr.co.board: DEBUG

bookstorage:
  # 이미지 호스팅
  image-host-url: http://localhost:8080/image
  # 업로드 설정
  upload:
    path: /Users/ksb/Documents/data/images

---
spring:
  profiles: security-on

---
spring:
  profiles: security
  jpa:
    hibernate:
      ddl-auto: none

management:
  security:
    sessions: ALWAYS
